name: odyssey_flutter_app
description: "odyssey_log_app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  flutter_dotenv: ^5.0.3
  flutter_naver_map: ^1.2.2

  geolocator: ^11.0.0

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.1

  http: ^0.13.3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  assets:
    - .env

  uses-material-design: true
